# Generated by Django 5.1.7 on 2025-04-03 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="networknode",
            options={"verbose_name": "Сеть", "verbose_name_plural": "Сети"},
        ),
        migrations.AddField(
            model_name="contacts",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите создателя контакта",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="networknode",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите создателя звена сети",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="network_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Укажите создателя продукта",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создатель",
            ),
        ),
    ]
